/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{astro,html,js,ts,jsx,tsx,svg}",
  ],
  theme: {
    extend: {
      colors: {
        'custom-dark-blue': '#7cbcfc',
        'custom-light-blue': '#c3f9fc',
        'custom-light-beige': '#F5F5DC',
        'custom-light-gray': '#D3D3D3',
        'custom-piel': '#CBA486',
        'custom-cafe': '#241E1A',
        'custom-gray': '#818185',
        'custom-azulpastel': '#758bfd',
        'custom-blueobscure': '#101a36',
        'custom-background-second': '#feefe8',
        'custmom-indigo-background' : '#f4effc',
        'custmom-indigo-cards' : '#e2daeb',
        'pastel-blue-soft': '#B3CDE0',
        'pastel-blue-medium': '#9EB4D4',
        'pastel-blue-strong': '#6D9DC5',

        'pastel-green-soft': '#B9D9B8',
        'pastel-green-medium': '#A1D0A1',
        'pastel-green-strong': '#6CBF6A',

        'pastel-pink-soft': '#F4A6A1',
        'pastel-pink-medium': '#F17E7A',
        'pastel-pink-strong': '#E94A4A',

        'pastel-mint-soft': '#A2D9A2',
        'pastel-mint-medium': '#85C785',
        'pastel-mint-strong': '#6AB86A',

        'pastel-peach-soft': '#F8D1C3',
        'pastel-peach-medium': '#F4B8A1',
        'pastel-peach-strong': '#F08060',
        'pastel-soft': '#E6E6FA',
        
        'pastel-medium': '#D5B4E8',
        'pastel-strong': '#B39DDB',
        'aqua-soft': '#E0FFFF',
        'aqua-medium': '#00CED1',
        'aqua-strong': '#20B2AA',
        'aqua-silver-soft': '#B2BEB5',
        'aqua-silver-medium': '#8B8D8F',
        'aqua-silver-strong': '#6C6E6B',
      },
      fontFamily: {
        cursive: ['Brush Script MT', 'cursive'],
        montserrat: ['Montserrat', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        opensans: ['Open Sans', 'sans-serif'],
        merriweather: ['Merriweather', 'serif'],
        robotoslab: ['Roboto Slab', 'serif'],
        lora: ['Lora', 'serif'],
        playfair: ['Playfair Display', 'serif'],
        dancing: ['Dancing Script', 'cursive'],
        bitter: ['Bitter', 'serif'],
        oswald: ['Oswald', 'sans-serif'],
        raleway: ['Raleway', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        bebas: ['Bebas Neue', 'sans-serif'],
        oswald: ['Oswald', 'sans-serif'],
      },
      screens: {
        'xs': '320px',
        'sm': '640px',
        'md': '760px',
        'lg': '830px',
        'xl': '1280px',
        '2xl': '1536px',
        'hide-img': {'min': '200px', 'max': '820px'},
      },
    },
  },
  plugins: [
    require('tailwind-clip-path'),
  ],
}